name: Build, Test, and Release utouch

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"  # Triggers release workflow on version tags like v1.0.0
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the project
      run: make

    - name: Run tests (if applicable)
      run: make check

    - name: Clean build files
      run: make clean

  release:
    # This depends on the build job to ensure release happens only after a successful build
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Ensure this runs only on tag pushes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the project (for release)
      run: make

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload executable to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        asset_path: utouch
        asset_name: utouch
        asset_content_type: application/octet-stream
